[package]
name = "minisat"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]
build = "build.rs"

readme="README.md"
documentation="https://docs.rs/minisat"
repository="https://github.com/luteberget/minisat-rs/"

[dependencies]
[build-dependencies]
cc="1"
bindgen="0.42"
